### ISSUE TITLE
login.html references wrong CSS

### ISSUE THREAD

**Issue by StefanCodes** [coofercat/peeked#1]
At the top of login.html, there's a link tag:

``` HTML
<link rel="stylesheet" href="{{ base_url }}/plugins/peeked/pico_editor.css" type="text/css" />
```

It looks like the CSS filename was changed at some point. This works:

``` HTML
<link rel="stylesheet" href="{{ base_url }}/plugins/peeked/peeked.css" type="text/css" />
```

**Comment by coofercat** [comment]
Whoops! Absolutely correct - thanks for reporting it. I missed this one when I forked it. Fixed :-)
