### ISSUE TITLE
No icons for View and Delete file

### ISSUE THREAD

**Issue by aaaton** [coofercat/peeked#3]
There are no icons visible for the View and Delete buttons as seen on this [screenshot](https://dl.dropboxusercontent.com/u/4620108/broken_icons.png). A wild guess is that it could have something to do with the 404 of this js file:

```
 Failed to load resource: the server responded with a status of 404 (Not Found)
 http://localhost/pico/plugins/peeked/top_up-1.7.2/top_up-min.js 
```

Or maybe some font is lacking?

BR
AAAton

**Comment by coofercat** [comment]
Peeked is forked from Pico Editor, in which those ions are only visible when you hover over the row in the file chooser. However, in Peeked, the 'delete' icon doesn't show correctly - it shows as a few pixels, but it should look like a little dustbin (I've tried to fix it, but honestly I can't figure it out). 

top_up-min.js is indeed missing - I'm not sure how I missed that, but the reference to it shouldn't be in the HTML at all, so I've removed it. Thanks for reporting it.
